name: debug_grid
description: A simple debug grid polymer element
author: Matias Meno <m@tias.me>
homepage: https://github.com/exitlive/debug-grid
version: "0.1.1"
dependencies:
    polymer: ">=0.12.0 <0.13.0"
    cookie: ">=0.0.4 <0.1.0"
transformers:
- polymer:
    entry_points: web/debug_grid.html
