name: debug_grid
description: A simple debug grid polymer element
author: Matias Meno <m@tias.me>
homepage: https://github.com/exitlive/debug-grid
version: "0.3.0"
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
    polymer: 1.0.0-rc.15
    polymer_elements: 1.0.0-rc.8
    cookie: ">=0.0.4 <0.1.0"
transformers:
- polymer:
    entry_points: web/debug_grid.html
